### PR TITLE
Requesting that DDVK's changes be merged

### PR DESCRIPTION
**Pull request by makbeta**
Kindly requesting for the DDVK's contributions to be merged, so his changes are incorporated in a future releases. 
His changes bring a few improvements and would be nice to have in all few Toltec releases of the keywriter. 
Thank you.

### CODE REVIEW

**Comment by Eeems** [comment]
@dps poke?

**Comment by dps** [comment]
I merged this PR but it broke the continuous build - will take a look at that tonight

**Comment by simonante** [comment]
Any chance incorporating [danschrage/remarkable-keywriter](https://github.com/danschrage/remarkable-keywriter/commit/56d341c339993c1016fb3097371b024c5bd2d849) edit mode font decrease? I.e. preview keep 12, but edit decrease to 11? Or not worth it?

**Comment by Eeems** [comment]
> Any chance incorporating [danschrage/remarkable-keywriter](https://github.com/danschrage/remarkable-keywriter/commit/56d341c339993c1016fb3097371b024c5bd2d849) edit mode font decrease? I.e. preview keep 12, but edit decrease to 11? Or not worth it?

#21 would be the place for this conversation.

**Comment by dps** [comment]
FYI, build fixed - PR is good - thank you!

**Pull request merged**
