### PR TITLE
Add install instructions for toltec users.

### PR DESCRIPTION
**Pull request by Eeems**

### CODE REVIEW

**Comment by matteodelabre** [comment]
You probably want to link to <https://github.com/toltec-dev/toltec> instead of <https://github.com/matteodelabre/toltec>. I’m not sure how long GitHub is going to keep the redirect working.

**Comment by Eeems** [comment]
> 
> 
> You probably want to link to https://github.com/toltec-dev/toltec instead of https://github.com/matteodelabre/toltec. I’m not sure how long GitHub is going to keep the redirect working.

It might actually make sense to link to https://toltec-dev.org/ now

**Comment by josuevalrob** [comment]
maybe is not related but: 
```
reMarkable: ~/ opkg install keywriter
Installing keywriter (0.1.0-3) to root...
Downloading https://toltec-dev.org/testing/rmall/keywriter_0.1.0-3_rmall.ipk
Collected errors:
 * opkg_download: Failed to download https://toltec-dev.org/testing/rmall/keywriter_0.1.0-3_rmall.ipk, wget returned 4.
 * opkg_download: Check your network settings and connectivity.

 * opkg_install_pkg: Failed to download keywriter. Perhaps you need to run 'opkg update'?
 * opkg_install_cmd: Cannot install package keywriter.
```

**Comment by Eeems** [comment]
@dps poke?

**Pull request merged**
